# Generated by Django 4.0.6 on 2022-08-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heelingminds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='webinars',
        ),
    ]
