# Generated by Django 4.0.6 on 2022-08-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_therapy_webinars_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='age',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapy',
            name='gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapy',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='webinars',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
