# Generated by Django 4.0.6 on 2022-08-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_therapy_age_therapy_gender_alter_therapy_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='therapy',
            new_name='therapies',
        ),
    ]
