# Generated by Django 4.0.6 on 2022-09-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_therapy_therapies'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=12)),
            ],
        ),
    ]
