# Generated by Django 4.0.6 on 2022-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_consultations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='disease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
