# Generated by Django 4.0.6 on 2022-09-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_consultations_email_alter_consultations_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consultations',
        ),
        migrations.AddField(
            model_name='webinars',
            name='disease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
