# Generated by Django 4.0.6 on 2022-09-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_consultations_webinars_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinars',
            name='disease',
        ),
    ]
