# Generated by Django 4.0.6 on 2022-09-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_webinars_disease'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='webinars',
            new_name='enquiry',
        ),
    ]
