# Generated by Django 4.0.6 on 2022-09-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_webinars_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapies',
            name='message',
        ),
    ]
